### ISSUE TITLE
make check broken?

### ISSUE THREAD

**Issue by kript** [swcarpentry/web-data-python#6]
Could just be my 'holding it wrong' as it were, but I get the following when trying to run 'make check';
'''
mib106284i:web-data-python jc18$ make check
python tools/check.py .
Traceback (most recent call last):
 File "tools/check.py", line 23, in <module>
   import CommonMark
ImportError: No module named CommonMark
make: **\* [check] Error 1
'''

**Comment by gvwilson** [comment]
'pip install commonmark' should fix this - please give it a try and let 
me know?
Thx,
G

On 2015-04-28 5:08 PM, John Constable wrote:

> Could just be my 'holding it wrong' as it were, but I get the 
> following when trying to run 'make check';
> '''
> mib106284i:web-data-python jc18$ make check
> python tools/check.py .
> Traceback (most recent call last):
> File "tools/check.py", line 23, in
> import CommonMark
> ImportError: No module named CommonMark
> make: **\* [check] Error 1
> '''
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/swcarpentry/web-data-python/issues/6.

## 

Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by rgaiacs** [comment]
@kript please try

```
$ sudo pip install -r requirements.txt
```

It will install all the packages that you need to run `tools/check.py`.

**Comment by kript** [comment]
Thanks both (especially r-gala-ca, can't believe I missed that!), that got me past the tools issue. On a  file I hadn't touched I now get;
python tools/check.py .
ERROR: In ./reference.md: At glossary entry 'comma-separated values (CSV):' Subsequent lines of definition must start with '     '.
WARNING: Some errors were encountered during validation. See log for details.
make: **\* [check] Error 1

but this is probably a separate issue.. :-)

**Comment by rgaiacs** [comment]
> can't believe I missed that!

No problem.

> On a file I hadn't touched I now get;
> 
> ```
> python tools/check.py .
> ERROR: In ./reference.md: At glossary entry 'comma-separated values (CSV):' Subsequent lines of definition must start with ' '.
> ```

You will find the explanation about it at https://github.com/swcarpentry/lesson-template/pull/177#issuecomment-74356218.
